package test.automator.control.excel.write;

import java.io.IOException;

public class Test {

    public static void main(final String[] args) throws IOException {
        // File excel = new File("C:/AutoGeneratedFiles_V2/TestDataFiles/NewTestDataTemplate.xls");
        // FileInputStream fis = new FileInputStream(excel);
        // Workbook workbook = new HSSFWorkbook(fis);
        // String safeName = WorkbookUtil.createSafeSheetName("acassascsasdfgsdgsdfgsggsdgfsdsfff"); // this utility replaces invalid characters with a space (' ')
        // workbook.setSheetName(0, safeName);
        // FileOutputStream fos = new FileOutputStream("C:/AutoGeneratedFiles_V2/TestDataFiles/NewTestDataTemplate.xls");
        // workbook.write(fos);
        // fos.close();
    }
}
