package test.automator.constants;

/**
 * This class defiles commonly used constants across different packages.
 * This is the location to update different properties w.r.to Automator
 * 
 * @author kamalesh.p
 * 
 */
public class Constants {

    private Constants() {
    }

    public static final String CONFIG_FILE_NAME                     = "TestSpecConfig.Properties";
    public static final String OUT_FILE_PATH                        = "c:/AutoGeneratedFiles_V3";
    // DEFAULT NAME FOR FILES TO BE GENERATED
    public static String       DEFAULT_TEST_SPEC_NAME               = "NewTestSpec.xlsx";
    public static String       DEFAULT_REQUEST_HANDLER_SCRIPT_NAME  = "RequestHandler.groovy";
    public static String       DEFAULT_GROOVY_SCRIPT_NAME           = "GroovyScript.groovy";
    public static String       DEFAULT_JSON_BUILDER_NAME            = "JSONBuilder.groovy";
    public static String       DEFAULT_REST_GROOVYSCRIPT_NAME       = "RESTGroovyScript.groovy";
    public static String       DEFAULT_PROPERTY_FILE_NAME           = "property.txt";
    public static String       DEFAULT_TEST_DATA_FILE_NAME          = "NewTestData.xls";
    public static String       DEFAULT_TEST_DATA_FILE_NAME_XLSX     = "NewTestData.xlsx";
    public static String       DEFAULT_TEST_DATA_TEMPLATE_NAME      = "NewTestDataTemplate.xls";
    public static String       DEFAULT_TEST_DATA_TEMPLATE_NAME_XLSX = "NewTestDataTemplate.xlsx";
    // User input SOPA or REST service.
    public static String       SOAP_OR_REST                         = null;
    public static final String SOAP_SERVICE                         = "SOAP";
    public static final String REST_SERVICE                         = "REST";
    public static boolean      EDIT_NODE_NAMES_IN_SCRIPTS           = true;
    // AUTOMATOR CONFIG FILE DETAILS
    public static String       GENERATE_TEST_CASE;

    public static String       VALID_SCENARIO;
    public static String       NULL_VALIDATION;
    public static String       DATA_TYPE_VALIDATION;
    public static String       DATE_VALIDATION                      = "N";
    public static String       BOOLEAN_VALIDATION                   = "N";
    public static String       INVALID_CHECK;
    public static String       BVA_VALIDATION;
    public static String       FAULT_STRING_SCRIPT;

    public static String       KEEP_UNDERSCORE;
    public static String       USE_COMMON_UTIL_LIB;
    public static String       COMMON_LIBRARY_NAME;

    public static String       TEST_SPEC_TEMPLATE_NAME;
    public static String       TEST_DATA_TEMPLATE_NAME;
    public static String       TEST_INPUT_DATA_FILE_NAME;

    public static String       PATH_TO_TESTSPEC_TEMPLATE_EXCEL;
    public static String       PATH_TO_TESTDATA_TEMPLATE_EXCEL;
    public static String       PATH_TO_TEST_GENERATOR_EXCEL;
    // FILE READER CONSTANTS USED IN COMMON METHODS (TEST CASE GENERATOR)
    public static final String MANDATORY                            = "Mandatory";
    public static final String NON_MANDATORY                        = "NonMandatory";
    public static final String NULL                                 = "NULL";
    public static final String UNBOUND                              = "UNBOUND";
    public static final String ALPHA_16                             = "asdfghjkWERTYuio";
    public static final String NUMERIC_10                           = "0123456789";
    public static final String ALPHA_NUM_20                         = "ASDFghjklW0123456789";
    public static final String SPECIAL_CHAR_20                      = "���~!@#$%^&*()���;/?";
    // input shhet number
    public static String       SERVICE_NAME                         = "";
    public static String       OPERATION_NAME                       = "";
    public static Boolean      UPDATE_NEWFILES_NAMES                = false;
}
